# 1. Usamos una imagen ligera de Node
FROM node:20-slim

# 2. Instalamos PostgreSQL dentro del contenedor
# 'apt-get install' es el comando de Linux para instalar programas
RUN apt-get update && apt-get install -y \
    postgresql \
    postgresql-contrib \
    && rm -rf /var/lib/apt/lists/*

# 3. Creamos la carpeta donde vivirá tu código
WORKDIR /app

# 4. Copiamos los archivos de configuración de Node primero (mejora la velocidad)
COPY package*.json ./
RUN npm install

# 5. Copiamos el resto de tu código (incluyendo el start.sh)
COPY . .

# 6. IMPORTANTE: Damos permiso de ejecución al script de arranque
RUN chmod +x /app/start.sh

# 7. Avisamos que tu app de Node usará el puerto 3000
EXPOSE 3070

# 8. El comando que Docker ejecutará al encenderse
CMD ["/app/start.sh"]